name: sd38-district-website
recipe: platformsh
config:
  id: 4rgkkoz2zwote
  webroot: web

# These are tools that are commonly used during development for this template.
tooling:
  drush:
    service: app
  drupal:
    service: app
