block_class_select.settings:
  type: config_object
  label: Block Class Select settings
  mapping:
    classes:
      type: sequence
      label: 'Allowed Classes List'
      sequence:
        type: string
    multiple:
      type: boolean
      label: 'Allow Multiple Class Selections'
    label:
      type: string
      label: 'Widget Label'
    description:
      type: string
      label: 'Widget Description'
